### ISSUE TITLE
similarity threshold used for paper

### ISSUE THREAD

**Issue by daphnei** [uralik/beamdream#1]
I was wondering what value is being used for the $$\epsilon$$ in equation 3 of the paper.
I see that a variable `min_hamming_dist` gets passed into `advance` in `beam_on_steroids.py`, but it doesn't look like it actually gets used. 
Was $$\epsilon=1$$ used for all the experiments in the paper? In this case, wouldn't this mean no relaxation is happening?

**Comment by uralik** [comment]
hi! yes for all experiments epsilon=1 was used. We have also tried values 2,3 during the implementation phase, but it did not change the candidates set that much. But that it also model/beam size/data dependent thing. And you are correct, in case of epsilon one no relaxation is happening there.

Iterbeam will be ported into new TorchGeneratorAgent in ParlAI soon (see for example: https://github.com/facebookresearch/ParlAI/pull/1355) where min distance is configurable and can be tried out.

I close it now, feel free to re-open again if you have further questions.

**Comment by daphnei** [comment]
Thanks for your quick response. We are trying to implement it into OpenNMT. I'll let you know if it ends up in there. :)
